spring:
  config:
    import:
      - classpath:application.yaml
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/wink}
    redis:
      host: ${REDIS_HOST:localhost}
      password: ${REDIS_PASSWORD:root}
      port: ${REDIS_PORT:6379}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

app:
  jwt:
    key: ${JWT_SECRET_KEY}
  sms:
    id: ${SMS_ID}
    pw: ${SMS_PASSWORD}
    send_phone: ${SMS_PHONE_NUMBER}
  cloud:
    aws:
      region: ${AWS_REGION:ap-northeast-2}
      s3:
        bucket: ${AWS_S3_BUCKET}
      credential:
        accessKey: ${AWS_ACCESS_KEY}
        secretKey: ${AWS_SECRET_KEY}
