spring:
  config:
    import:
      - classpath:config/aws.yaml
      - classpath:config/google.yaml
      - classpath:config/jwt.yaml
      - classpath:config/mail.yaml
      - classpath:config/mongo.yaml
      - classpath:config/notion.yaml
      - classpath:config/redis.yaml
      - classpath:config/server.fixed.yaml
      - classpath:config/sms.yaml
      - classpath:config/swagger.fixed.yaml
