server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: test
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    key: secret
    access-token-expiration-hours: 1
    refresh-token-expiration-hours: 720
  cloud:
    aws:
      region: ap-northeast-2
      s3:
        bucket: bucket
      credential:
        accessKey: access
        secretKey: secret
  sms:
    id: test
    pw: test
    phoneNumber: 010-0000-0000