server:
  forward-headers-strategy: NATIVE
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  mail:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    log-resolved-exception: false

app:
  jwt:
    access-token-expiration-hours: 4
    refresh-token-expiration-hours: 168

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: -1
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
  cache:
    disabled: true
