server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force-response: true

spring:
  mvc:
    log-resolved-exception: false
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: myuser
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  jwt:
    key: (secret-key)
    access-token-expiration-hours: 1
    refresh-token-expiration-hours: 720