export enum Role {
  PRESIDENT = 'PRESIDENT',
  VICE_PRESIDENT = 'VICE_PRESIDENT',
  TREASURY_HEAD = 'TREASURY_HEAD',
  TREASURY_ASSISTANT = 'TREASURY_ASSISTANT',
  PUBLIC_RELATIONS_HEAD = 'PUBLIC_RELATIONS_HEAD',
  PUBLIC_RELATIONS_ASSISTANT = 'PUBLIC_RELATIONS_ASSISTANT',
  PLANNING_HEAD = 'PLANNING_HEAD',
  PLANNING_ASSISTANT = 'PLANNING_ASSISTANT',
  MEMBER = 'MEMBER',
}
