package com.github.kmu_wink.wink_official.domain.recruit.constant;

public enum FormEntryKeys {
	// 필수
	NAME, STUDENT_ID, EMAIL, PHONE_NUMBER, JIWON_DONGGI, BAEUGO_SIPEUN_JEOM, CAN_INTERVIEW_DATES, DOMAIN,

	// 선택
	GITHUB, FRONTEND_TECH_STACKS, BACKEND_TECH_STACKS, DATABASE_TECH_STACKS, DEV_OPS_TECH_STACKS, DESIGN_TECH_STACKS, FAVORITE_PROJECT, LAST_COMMENT,
}