package com.github.kmu_wink.wink_official.domain.recruit.constant;

public enum FormEntryKeys {
	NAME, STUDENT_ID, DEPARTMENT, EMAIL, PHONE_NUMBER, JIWON_DONGGI, SELF_INTRODUCE, OUTINGS, INTERVIEW_DATES, WHY_CANNOT_INTERVIEW,
	GITHUB, FRONTEND_TECH_STACKS, BACKEND_TECH_STACKS, DEV_OPS_TECH_STACKS, DESIGN_TECH_STACKS, FAVORITE_PROJECT,
}


