redis:
  host: ${REDIS_HOST:=localhost}
  port: ${REDIS_PORT:=6379}

mongo:
  host: ${MONGO_HOST:=localhost}
  port: ${MONGO_PORT:=27017}
  username: ${MONGO_USERNAME:=''}
  password: ${MONGO_PASSWORD:=''}
  authSource: ${MONGO_AUTH_SOURCE:=''}
  database: ${MONGO_DATABASE:=wink}

smtp:
  host: ${SMTP_HOST:=smtp.gmail.com}
  port: ${SMTP_PORT:=465}
  secure: ${SMTP_SECURE:=true}
  username: ${SMTP_USERNAME:=''}
  password: ${SMTP_PASSWORD:=''}

s3:
  region: ${S3_REGION:=ap-northeast-2}
  bucket: ${S3_BUCKET:=''}
  credentials:
    accessKey: ${S3_ACCESS_KEY:=''}
    secretKey: ${S3_SECRET_KEY:=''}

jwt:
  secret: ${JWT_SECRET:=secret}
  expiresIn:
    access: ${JWT_EXPIRES_IN_ACCESS:=1h}
    refresh: ${JWT_EXPIRES_IN_REFRESH:=7d}
