redis:
  host: (Redis host, default localhost)
  port: (Redis port, default 6379)

mongo:
  host: (MongoDB host, default localhost)
  port: (MongoDB port, default 27017)
  username: (MongoDB username, default '')
  password: (MongoDB password, default '')
  authSource: (MongoDB authSource, default '')
  database: (MongoDB database, default 'test')
