redis:
  host: ${REDIS_HOST:=redis}
  port: ${REDIS_PORT:=6379}

mongo:
  host: ${MONGO_HOST:=mongo}
  port: ${MONGO_PORT:=27017}
  username: ${MONGO_USERNAME:=''}
  password: ${MONGO_PASSWORD:=''}
  authSource: ${MONGO_AUTH_SOURCE:=''}
  database: ${MONGO_DATABASE:=test}
