name: Build

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
      - develop

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-master:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ioloolo/wink-official-backend:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ioloolo/wink-official-backend:buildcache
          cache-to: type=registry,ref=ioloolo/wink-official-backend:buildcache,mode=max

  build-develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ioloolo/wink-official-backend:develop
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=ioloolo/wink-official-backend:buildcache-develop
          cache-to: type=registry,ref=ioloolo/wink-official-backend:buildcache-develop,mode=max
