name: Test and Deploy

on:
  push:
    paths:
      - 'src/**'
      - 'package.json'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Get yarn cache directory
        id: yarn-cache-dir-path
        shell: bash
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache yarn packages and node_modules
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOSTNAME }} << 'EOF'
            cd ~/wink-official-backend
          
            git pull origin develop
          
            echo "${{ secrets.CICD_DOCKER_ENV }}" > cicd.docker.env
          
            docker compose build
            docker compose down
            docker compose up -d
          EOF
