name: Test
run-name: Test on ${{ github.ref }} (${{ github.sha }})

on:
  push: {}

concurrency:
  group: test-${{ github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn test
