name: Update Deploy Repository

on:
  push:
    branches:
      - master
      - develop

jobs:
  update-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout deploy repository
        run: |
          git clone --branch ${{ github.ref_name }} https://github.com/kmu-wink/wink-official-deploy.git deploy
          cd deploy
          git checkout ${{ github.ref_name }}
          git submodule update --remote backend

      - name: Commit and push changes
        run: |
          cd deploy
          git add backend
          git commit -m "update: backend (from ${{ github.sha }})"
          git push origin ${{ github.ref_name }}
