name: Update Deploy Repository
run-name: Update on ${{ github.ref_name }}

on:
  push:
    branches:
      - master
      - develop

jobs:
  update-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_GITHUB_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Repository
        run: |
          git clone --branch ${{ github.ref_name }} git@github.com:kmu-wink/wink-official-deploy.git deploy
          cd deploy
      
      - name: Update Submodule
        run: |
          git submodule update --remote backend
          git add backend
          git commit -m "update: backend (from ${{ github.sha }})"
          git push origin ${{ github.ref_name }}
