name: Update to Deploy Repository
run-name: Update to Deploy Repository (${{ github.event.workflow_run.head_branch }})

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed
    branches:
      - master
      - develop

concurrency:
  group: update-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  update-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: kmu-wink/wink-official-deploy
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: recursive
          ssh-key: ${{ github.secrets.SSH_GITHUB_KEY }}
        
      - name: Set up Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Update Submodule
        run: |
          git submodule update --remote backend
          
      - name: Commit and Push
        run: |
          git add backend
          git commit -m "update: backend"
          git push origin ${{ github.event.workflow_run.head_branch }}
